version: '3.8'

services:
  account-management-backend:
    image: "ashrafulsohag/accounts:config"
    container_name: account-service-02
    restart: always
    ports:
      - 9080:9080

    networks:
      - accountservice

    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_CONFIG_IMPORT: configserver:http://nginx:5000/
      # here first configserver is spring format, and second configserver is docker service name
      SPRING_PROFILES_ACTIVE: dv-02
      SPRING_RABBIT_HOST: rabbit
      SPRING_RABBIT_PORT: 5672

networks:
  accountservice:
    external: true